### ISSUE TITLE
Error with execution

### ISSUE THREAD

**Issue by sakebomb** [Eijebong/BeetleBot#1]
From a clean install, I get this error.

Traceback (most recent call last):
  File "bot.py", line 241, in <module>
    apis = {project: api.GitlabAPI(cnf['gitlab']['base_url'], cnf['gitlab']['main_key'], cnf['keys'], project, branch) for room, projects in cnf['rooms'].items() for project, branch in projects.items()}
  File "bot.py", line 241, in <dictcomp>
    apis = {project: api.GitlabAPI(cnf['gitlab']['base_url'], cnf['gitlab']['main_key'], cnf['keys'], project, branch) for room, projects in cnf['rooms'].items() for project, branch in projects.items()}
  File "/home/sakebomb/BeetleBot-master/api.py", line 106, in **init**
    self.project_id = self.get_project_by_name(project_name, use_cache)
  File "/home/sakebomb/BeetleBot-master/api.py", line 58, in get_project_by_name
    req = self.do_request("projects", "GET")
  File "/home/sakebomb/BeetleBot-master/api.py", line 37, in do_request
    r = getattr(requests, method.lower())(url, headers=headers, json=content)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 55, in get
    return request('get', url, *_kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, *_kwargs)
TypeError: request() got an unexpected keyword argument 'json'

**Comment by Eijebong** [comment]
Weird, what is your python / requests version ?

**Comment by sakebomb** [comment]
Python 3.4.3 - requests 2.2.1

**Comment by Eijebong** [comment]
I just pushed a full rewrite of the bot. Sorry I never got to look at this in details :/
